version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-lexartlabs
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  app:
    build:
      context: .
    container_name: backend-test
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/products
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - my-network
    depends_on:
      - mysql
volumes:
  mysql-data:
    driver: local

networks:
  my-network:
    driver: bridge